```js
const asyncFun = (b) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const a = Math.random()
      if (a > b) {
        resolve(a)
      } else {
        reject(new Error('error'))
      }
    }, 0)
  })
}

asyncFun(0.3)
  .then(a => a + 1)
  .then(res => console.log(res))
  .catch(err => console.log(err))
```
